# build step
FROM node:12-alpine AS build

WORKDIR /devel

COPY package.json .
COPY yarn.lock .

COPY frontend frontend
COPY packages packages

RUN yarn install --non-interactive --frozen-lockfile

COPY . .

RUN yarn build:frontend

# serve step
FROM nginx:1.17-alpine AS serve

WORKDIR /var/www/magnit

COPY --from=build /devel/frontend/build .
COPY nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
