FROM node:10-alpine

WORKDIR /devel

COPY . .

RUN chmod +x gen_backend_config.sh \
 && ./gen_backend_config.sh \
 && yarn install \
 && cd packages/backend \
 && npm i

ENTRYPOINT ["yarn", "start:backend"]
